- name: Install all apps server
  apt:
    name: "{{ apps }}"
    state: present
    update_cache: yes
  become: true

- name: Upload index.php file
  copy:
    src: ./config/index.php
    dest: /var/www/html
    mode: 07555
  become: true

- name: Upload config file in load balancer
  copy:
    src: ./config/loadbalancer.conf
    dest: /etc/apache2/sites-available/000-default.conf
    mode: 0755
  become: true
  notify: Restart apache server